#& .github/workflows/deploy.yml
name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/webapp:latest .

    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/webapp:latest

    - name: Update K8s Manifest
      run: |
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/webapp:latest|" deploy/deployment.yaml
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "Updated image to latest"
        git push

